INSERT INTO settingparameters (ID, Name, Value) VALUES
(127, 'Logo', 'logo_20250905212444_9c3d835b.png'),
(128, 'LogoKop', 'logo_20250905212502_4ece33eb.jpg'),
(129, 'NPPPerpustakaan', '3273093A1000001'),
(130, 'EmailPerpustakaan', 'perpus@mail.go.id'),
(131, 'Instagram', '@dispusip7f'),
(132, 'Youtube', 'dispusip7f'),
(133, 'Facebook', 'test22f7'),
(134, 'Phone', '081180557777'),
(135, 'LayananOperasional', '&lt;b&gt;Jam Operasional Layanan&lt;/b&gt;&lt;br&gt;'),
(136, 'KartuAnggota1', '1756785115_27f0d1b82bbc25230614.png'),
(137, 'TulisanBanner', 'Selamat Datang di Perpustakaan Mitra'),
(138, 'SettingBukuTamu', '1'),
(139, 'TentangKami', 'Dinas Perpustakaan Mitra berkomitmen untuk menyediakan layanan perpustakaan berkualitas bagi');

ALTER TABLE members 
ADD COLUMN IsKeranjang INT NOT NULL DEFAULT 0;

ALTER TABLE members_form 
ADD COLUMN active INT NOT NULL DEFAULT 1;


ALTER TABLE catalogs
ADD COLUMN ISDRM INT NOT NULL DEFAULT 0;

ALTER TABLE collections
ADD COLUMN ISDRM INT NOT NULL DEFAULT 0;

ALTER TABLE collections
ADD COLUMN IsQUARANTINE INT NOT NULL DEFAULT 0;

-- 1. Lihat semua foreign key constraints
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE CONSTRAINT_SCHEMA = 'pustaka33' 
AND REFERENCED_TABLE_NAME IS NOT NULL;

-- 2. Drop foreign key (lakukan untuk setiap FK yang ditemukan)
ALTER TABLE nama_tabel DROP FOREIGN KEY nama_constraint;
		
-- Script untuk menghapus semua Foreign Key Constraints
-- PERINGATAN: Backup database terlebih dahulu sebelum menjalankan script ini!

-- Nonaktifkan foreign key checks sementara untuk mencegah error dependencies
SET FOREIGN_KEY_CHECKS = 0;

-- Drop semua foreign key constraints
ALTER TABLE agama DROP FOREIGN KEY agama_createby;
ALTER TABLE agama DROP FOREIGN KEY agama_updateby;
ALTER TABLE applications DROP FOREIGN KEY applications_createby;
ALTER TABLE applications DROP FOREIGN KEY applications_updateby;
ALTER TABLE auth_assignment DROP FOREIGN KEY auth_assignment_createby;
ALTER TABLE auth_assignment DROP FOREIGN KEY auth_assignment_ibfk_1;
ALTER TABLE auth_assignment DROP FOREIGN KEY auth_assignment_updateby;
ALTER TABLE auth_data DROP FOREIGN KEY auth_data_auth_header;
ALTER TABLE auth_data DROP FOREIGN KEY auth_data_createby;
ALTER TABLE auth_data DROP FOREIGN KEY auth_data_updateby;
ALTER TABLE auth_groups_permissions DROP FOREIGN KEY auth_groups_permissions_ibfk_1;
ALTER TABLE auth_groups_permissions DROP FOREIGN KEY auth_groups_permissions_ibfk_2;
ALTER TABLE auth_groups_users DROP FOREIGN KEY auth_groups_users_ibfk_1;
ALTER TABLE auth_groups_users DROP FOREIGN KEY auth_groups_users_ibfk_2;
ALTER TABLE auth_header DROP FOREIGN KEY auth_header_createby;
ALTER TABLE auth_header DROP FOREIGN KEY auth_header_updateby;
ALTER TABLE auth_header DROP FOREIGN KEY auth_header_worksheet_id;
ALTER TABLE auth_item DROP FOREIGN KEY auth_item_createby;
ALTER TABLE auth_item DROP FOREIGN KEY auth_item_ibfk_1;
ALTER TABLE auth_item DROP FOREIGN KEY auth_item_updateby;
ALTER TABLE auth_item_child DROP FOREIGN KEY auth_item_child_createby;
ALTER TABLE auth_item_child DROP FOREIGN KEY auth_item_child_ibfk_1;
ALTER TABLE auth_item_child DROP FOREIGN KEY auth_item_child_ibfk_2;
ALTER TABLE auth_item_child DROP FOREIGN KEY auth_item_child_updateby;
ALTER TABLE auth_rule DROP FOREIGN KEY auth_rule_createby;
ALTER TABLE auth_rule DROP FOREIGN KEY auth_rule_updateby;
ALTER TABLE auth_tokens DROP FOREIGN KEY auth_tokens_ibfk_1;
ALTER TABLE auth_users_permissions DROP FOREIGN KEY auth_users_permissions_ibfk_1;
ALTER TABLE auth_users_permissions DROP FOREIGN KEY auth_users_permissions_ibfk_2;
ALTER TABLE bacaditempat DROP FOREIGN KEY bacaditempat_collections;
ALTER TABLE bacaditempat DROP FOREIGN KEY bacaditempat_createby;
ALTER TABLE bacaditempat DROP FOREIGN KEY bacaditempat_locations;
ALTER TABLE bacaditempat DROP FOREIGN KEY bacaditempat_members;
ALTER TABLE bibidavailable DROP FOREIGN KEY bibidavailable_createby;
ALTER TABLE bibidavailable DROP FOREIGN KEY bibidavailable_updateby;
ALTER TABLE bookinglogs DROP FOREIGN KEY fk_bookinglogs_memberId;
ALTER TABLE bookmark DROP FOREIGN KEY bookmark_createby;
ALTER TABLE bookmark DROP FOREIGN KEY bookmark_updateby;
ALTER TABLE branchs DROP FOREIGN KEY branchs_createby;
ALTER TABLE branchs DROP FOREIGN KEY branchs_updateby;
ALTER TABLE cardformats DROP FOREIGN KEY cardformats_createby;
ALTER TABLE cardformats DROP FOREIGN KEY cardformats_updateby;
ALTER TABLE catalog_ruas DROP FOREIGN KEY catalog_ruas_catalogs;
ALTER TABLE catalog_ruas DROP FOREIGN KEY catalog_ruas_createby;
ALTER TABLE catalog_ruas DROP FOREIGN KEY catalog_ruas_updateby;
ALTER TABLE catalog_subruas DROP FOREIGN KEY catalog_subruas_createby;
ALTER TABLE catalog_subruas DROP FOREIGN KEY catalog_subruas_ruas;
ALTER TABLE catalog_subruas DROP FOREIGN KEY catalog_subruas_updateby;
ALTER TABLE catalogfiles DROP FOREIGN KEY catalogfiles_catalog;
ALTER TABLE catalogfiles DROP FOREIGN KEY catalogfiles_createby;
ALTER TABLE catalogfiles DROP FOREIGN KEY catalogfiles_member;
ALTER TABLE catalogfiles DROP FOREIGN KEY catalogfiles_updateby;
ALTER TABLE catalogs DROP FOREIGN KEY catalogs_branch;
ALTER TABLE catalogs DROP FOREIGN KEY catalogs_createby;
ALTER TABLE catalogs DROP FOREIGN KEY catalogs_member;
ALTER TABLE catalogs DROP FOREIGN KEY catalogs_quarantinedby;
ALTER TABLE catalogs DROP FOREIGN KEY catalogs_updateby;
ALTER TABLE catalogs DROP FOREIGN KEY catalogs_worksheet;
ALTER TABLE catalogstaging DROP FOREIGN KEY catalogstaging_createby;
ALTER TABLE catalogstaging DROP FOREIGN KEY catalogstaging_updateby;
ALTER TABLE checkpoint_locations DROP FOREIGN KEY checkpoint_locations_createby;
ALTER TABLE checkpoint_locations DROP FOREIGN KEY checkpoint_locations_updateby;
ALTER TABLE checkpoint_locations DROP FOREIGN KEY FK_logincheckpoint_locations;
ALTER TABLE collectioncategorys DROP FOREIGN KEY collectioncategorys_createby;
ALTER TABLE collectioncategorys DROP FOREIGN KEY collectioncategorys_updateby;
ALTER TABLE collectioncategorysdefault DROP FOREIGN KEY collectioncategorysdefault_category;
ALTER TABLE collectioncategorysdefault DROP FOREIGN KEY collectioncategorysdefault_createby;
ALTER TABLE collectioncategorysdefault DROP FOREIGN KEY collectioncategorysdefault_jenis_anggota;
ALTER TABLE collectioncategorysdefault DROP FOREIGN KEY collectioncategorysdefault_updateby;
ALTER TABLE collectioncategorysloanhari DROP FOREIGN KEY collectioncategorysloanhari_category_id;
ALTER TABLE collectioncategorysloanhari DROP FOREIGN KEY collectioncategorysloanhari_createby;
ALTER TABLE collectioncategorysloanhari DROP FOREIGN KEY collectioncategorysloanhari_peminjaman_hari_id;
ALTER TABLE collectioncategorysloanhari DROP FOREIGN KEY collectioncategorysloanhari_updateby;
ALTER TABLE collectionloanextends DROP FOREIGN KEY collectionloanextends_col;
ALTER TABLE collectionloanextends DROP FOREIGN KEY collectionloanextends_colloan;
ALTER TABLE collectionloanextends DROP FOREIGN KEY collectionloanextends_colloanitem;
ALTER TABLE collectionloanextends DROP FOREIGN KEY collectionloanextends_createby;
ALTER TABLE collectionloanextends DROP FOREIGN KEY collectionloanextends_member;
ALTER TABLE collectionloanextends DROP FOREIGN KEY collectionloanextends_updateby;
ALTER TABLE collectionloanitems DROP FOREIGN KEY collectionloanitems_col;
ALTER TABLE collectionloanitems DROP FOREIGN KEY collectionloanitems_colloan;
ALTER TABLE collectionloanitems DROP FOREIGN KEY collectionloanitems_createby;
ALTER TABLE collectionloanitems DROP FOREIGN KEY collectionloanitems_members;
ALTER TABLE collectionloanitems DROP FOREIGN KEY collectionloanitems_updateby;
ALTER TABLE collectionloans DROP FOREIGN KEY collectionloans_createby;
ALTER TABLE collectionloans DROP FOREIGN KEY collectionloans_updateby;
ALTER TABLE collectionloans DROP FOREIGN KEY FKA5D300395DD8E7A8;
ALTER TABLE collectionloans DROP FOREIGN KEY FKA5D300396ADC8006;
ALTER TABLE collectionloans DROP FOREIGN KEY FK_collectionloans_location_library;
ALTER TABLE collectionlocations DROP FOREIGN KEY collectionlocations_createby;
ALTER TABLE collectionlocations DROP FOREIGN KEY collectionlocations_updateby;
ALTER TABLE collectionmedias DROP FOREIGN KEY collectionmedias_createby;
ALTER TABLE collectionmedias DROP FOREIGN KEY collectionmedias_updateby;
ALTER TABLE collectionmedias DROP FOREIGN KEY collectionmedias_worksheet;
ALTER TABLE collectionrules DROP FOREIGN KEY collectionrules_createby;
ALTER TABLE collectionrules DROP FOREIGN KEY collectionrules_updateby;
ALTER TABLE collectionrulesitems DROP FOREIGN KEY collectionrulesitems_createby;
ALTER TABLE collectionrulesitems DROP FOREIGN KEY collectionrulesitems_updateby;
ALTER TABLE collectionrulesitems DROP FOREIGN KEY FKA288C9A1451A301A;
ALTER TABLE collections DROP FOREIGN KEY collections_branch;
ALTER TABLE collections DROP FOREIGN KEY collections_catalog;
ALTER TABLE collections DROP FOREIGN KEY collections_category;
ALTER TABLE collections DROP FOREIGN KEY collections_createby;
ALTER TABLE collections DROP FOREIGN KEY collections_currency;
ALTER TABLE collections DROP FOREIGN KEY collections_deposit_ws_ID;
ALTER TABLE collections DROP FOREIGN KEY collections_jilidcreateby;
ALTER TABLE collections DROP FOREIGN KEY collections_location;
ALTER TABLE collections DROP FOREIGN KEY collections_location_library;
ALTER TABLE collections DROP FOREIGN KEY collections_media;
ALTER TABLE collections DROP FOREIGN KEY collections_partner;
ALTER TABLE collections DROP FOREIGN KEY collections_quarantinedby;
ALTER TABLE collections DROP FOREIGN KEY collections_rule;
ALTER TABLE collections DROP FOREIGN KEY collections_source;
ALTER TABLE collections DROP FOREIGN KEY collections_status;
ALTER TABLE collections DROP FOREIGN KEY collections_updateby;
ALTER TABLE collections DROP FOREIGN KEY collection_deposit_kode_wilayah_ID;
ALTER TABLE collectionsources DROP FOREIGN KEY collectionsources_createby;
ALTER TABLE collectionsources DROP FOREIGN KEY collectionsources_updateby;
ALTER TABLE collectionstatus DROP FOREIGN KEY collectionstatus_createby;
ALTER TABLE collectionstatus DROP FOREIGN KEY collectionstatus_updateby;
ALTER TABLE colloclib DROP FOREIGN KEY colloclib_createby;
ALTER TABLE colloclib DROP FOREIGN KEY colloclib_updateby;
ALTER TABLE colloclib DROP FOREIGN KEY FK_colloclib_col;
ALTER TABLE colloclib DROP FOREIGN KEY FK_colloclib_loclib;
ALTER TABLE currency DROP FOREIGN KEY currency_createby;
ALTER TABLE currency DROP FOREIGN KEY currency_updateby;
ALTER TABLE departments DROP FOREIGN KEY departments_createby;
ALTER TABLE departments DROP FOREIGN KEY departments_updateby;
ALTER TABLE departments DROP FOREIGN KEY FKFE0DEFC7922003A1;
ALTER TABLE deposit_group_ws DROP FOREIGN KEY deposit_group_ws_createby;
ALTER TABLE deposit_group_ws DROP FOREIGN KEY deposit_group_ws_updateby;
ALTER TABLE deposit_kelompok_penerbit DROP FOREIGN KEY deposit_kelompok_penerbit_createby;
ALTER TABLE deposit_kode_wilayah DROP FOREIGN KEY deposit_kode_wilayah_createby;
ALTER TABLE deposit_kode_wilayah DROP FOREIGN KEY deposit_kode_wilayah_updateby;
ALTER TABLE deposit_taksiran_harga DROP FOREIGN KEY colections_id;
ALTER TABLE deposit_ws DROP FOREIGN KEY `(ID)deposit_kelompok_penerbit`;
ALTER TABLE deposit_ws DROP FOREIGN KEY `(ID)deposit_kode_wilayah`;
ALTER TABLE deposit_ws DROP FOREIGN KEY `(id_group)group-ws`;
ALTER TABLE djkn_data DROP FOREIGN KEY djkn_data_collection;
ALTER TABLE djkn_data DROP FOREIGN KEY djkn_data_createby;
ALTER TABLE djkn_data DROP FOREIGN KEY djkn_data_updateby;
ALTER TABLE favorite DROP FOREIGN KEY FK_Catalog;
ALTER TABLE favorite DROP FOREIGN KEY FK_members;
ALTER TABLE fielddatas DROP FOREIGN KEY fielddatas_createby;
ALTER TABLE fielddatas DROP FOREIGN KEY fielddatas_fieldid;
ALTER TABLE fielddatas DROP FOREIGN KEY fielddatas_updateby;
ALTER TABLE fieldgroups DROP FOREIGN KEY fieldgroups_createby;
ALTER TABLE fieldgroups DROP FOREIGN KEY fieldgroups_updateby;
ALTER TABLE fieldindicator1s DROP FOREIGN KEY fieldindicator1s_createby;
ALTER TABLE fieldindicator1s DROP FOREIGN KEY fieldindicator1s_updateby;
ALTER TABLE fieldindicator1s DROP FOREIGN KEY FKBC43AFA166DFF9B4;
ALTER TABLE fieldindicator2s DROP FOREIGN KEY fieldindicator2s_createby;
ALTER TABLE fieldindicator2s DROP FOREIGN KEY fieldindicator2s_updateby;
ALTER TABLE fieldindicator2s DROP FOREIGN KEY FKBC43AFA066DFF9B4;
ALTER TABLE fields DROP FOREIGN KEY fields_createby;
ALTER TABLE fields DROP FOREIGN KEY fields_fieldgroup;
ALTER TABLE fields DROP FOREIGN KEY fields_format;
ALTER TABLE fields DROP FOREIGN KEY fields_updateby;
ALTER TABLE formats DROP FOREIGN KEY formats_createby;
ALTER TABLE formats DROP FOREIGN KEY formats_updateby;
ALTER TABLE groupguesses DROP FOREIGN KEY groupguesses_createby;
ALTER TABLE groupguesses DROP FOREIGN KEY groupguesses_locations;
ALTER TABLE groupguesses DROP FOREIGN KEY groupguesses_loclib;
ALTER TABLE groupguesses DROP FOREIGN KEY groupguesses_tujuankunjungan_fk;
ALTER TABLE groupguesses DROP FOREIGN KEY groupguesses_updateby;
ALTER TABLE historydata DROP FOREIGN KEY historydata_createby;
ALTER TABLE historydata DROP FOREIGN KEY historydata_member;
ALTER TABLE historydata DROP FOREIGN KEY historydata_updateby;
ALTER TABLE holidays DROP FOREIGN KEY holidays_createby;
ALTER TABLE holidays DROP FOREIGN KEY holidays_updateby;
ALTER TABLE jenis_anggota DROP FOREIGN KEY jenis_anggota_createby;
ALTER TABLE jenis_anggota DROP FOREIGN KEY jenis_anggota_updateby;
ALTER TABLE jenis_denda DROP FOREIGN KEY jenis_denda_createby;
ALTER TABLE jenis_denda DROP FOREIGN KEY jenis_denda_updateby;
ALTER TABLE jenis_kelamin DROP FOREIGN KEY jenis_kelamin_createby;
ALTER TABLE jenis_kelamin DROP FOREIGN KEY jenis_kelamin_updateby;
ALTER TABLE jenis_pelanggaran DROP FOREIGN KEY jenis_pelanggaran_createby;
ALTER TABLE jenis_pelanggaran DROP FOREIGN KEY jenis_pelanggaran_updateby;
ALTER TABLE jenis_permohonan DROP FOREIGN KEY jenis_permohonan_createby;
ALTER TABLE jenis_permohonan DROP FOREIGN KEY jenis_permohonan_updateby;
ALTER TABLE jenis_perpustakaan DROP FOREIGN KEY jenis_perpustakaan_createby;
ALTER TABLE jenis_perpustakaan DROP FOREIGN KEY jenis_perpustakaan_updateby;
ALTER TABLE judul_koleksi DROP FOREIGN KEY judul_koleksi_createby;
ALTER TABLE judul_koleksi DROP FOREIGN KEY judul_koleksi_updateby;
ALTER TABLE kabupaten DROP FOREIGN KEY kabupaten_createby;
ALTER TABLE kabupaten DROP FOREIGN KEY kabupaten_propinsi;
ALTER TABLE kabupaten DROP FOREIGN KEY kabupaten_updateby;
ALTER TABLE kata_sandang DROP FOREIGN KEY kata_sandang_createby;
ALTER TABLE kata_sandang DROP FOREIGN KEY kata_sandang_updateby;
ALTER TABLE kelas_siswa DROP FOREIGN KEY kelas_siswa_createby;
ALTER TABLE kelas_siswa DROP FOREIGN KEY kelas_siswa_updateby;
ALTER TABLE kelompok_pelanggaran DROP FOREIGN KEY kelompok_pelanggaran_createby;
ALTER TABLE kelompok_pelanggaran DROP FOREIGN KEY kelompok_pelanggaran_updateby;
ALTER TABLE keranjang_anggota DROP FOREIGN KEY keranjang_anggota_createby;
ALTER TABLE keranjang_anggota DROP FOREIGN KEY keranjang_anggota_members;
ALTER TABLE keranjang_anggota DROP FOREIGN KEY keranjang_anggota_updateby;
ALTER TABLE keranjang_katalog DROP FOREIGN KEY keranjang_katalog_catalogs;
ALTER TABLE keranjang_katalog DROP FOREIGN KEY keranjang_katalog_createby;
ALTER TABLE keranjang_katalog DROP FOREIGN KEY keranjang_katalog_updateby;
ALTER TABLE keranjang_koleksi DROP FOREIGN KEY keranjang_koleksi_collection;
ALTER TABLE keranjang_koleksi DROP FOREIGN KEY keranjang_koleksi_createby;
ALTER TABLE keranjang_koleksi DROP FOREIGN KEY keranjang_koleksi_updateby;
ALTER TABLE kriteria_koleksi DROP FOREIGN KEY kriteria_koleksi_catalogby;
ALTER TABLE kriteria_koleksi DROP FOREIGN KEY kriteria_koleksi_createby;
ALTER TABLE kriteria_koleksi DROP FOREIGN KEY kriteria_koleksi_updateby;
ALTER TABLE letter DROP FOREIGN KEY `(ID)deposit_ws`;
ALTER TABLE letter DROP FOREIGN KEY letter_createby;
ALTER TABLE letter DROP FOREIGN KEY letter_updateby;
ALTER TABLE letter_detail DROP FOREIGN KEY `(ID)collectiomedias`;
ALTER TABLE letter_detail DROP FOREIGN KEY `(ID)letter`;
ALTER TABLE library DROP FOREIGN KEY library_createby;
ALTER TABLE library DROP FOREIGN KEY library_updateby;
ALTER TABLE librarysearchcriteria DROP FOREIGN KEY librarysearchcriteria_createby;
ALTER TABLE librarysearchcriteria DROP FOREIGN KEY librarysearchcriteria_library;
ALTER TABLE librarysearchcriteria DROP FOREIGN KEY librarysearchcriteria_updateby;
ALTER TABLE location_library DROP FOREIGN KEY location_library_createby;
ALTER TABLE location_library DROP FOREIGN KEY location_library_updateby;
ALTER TABLE location_library_default DROP FOREIGN KEY location_library_default_createby;
ALTER TABLE location_library_default DROP FOREIGN KEY location_library_default_jenis_anggota;
ALTER TABLE location_library_default DROP FOREIGN KEY location_library_default_loc;
ALTER TABLE location_library_default DROP FOREIGN KEY location_library_default_updateby;
ALTER TABLE locations DROP FOREIGN KEY locations_createby;
ALTER TABLE locations DROP FOREIGN KEY locations_loclib;
ALTER TABLE locations DROP FOREIGN KEY locations_updateby;
ALTER TABLE lockers DROP FOREIGN KEY fk_lockers_master_loker;
ALTER TABLE lockers DROP FOREIGN KEY lockers_createby;
ALTER TABLE lockers DROP FOREIGN KEY lockers_jenisidentitas;
ALTER TABLE lockers DROP FOREIGN KEY lockers_pelanggaran;
ALTER TABLE lockers DROP FOREIGN KEY lockers_uangjaminan;
ALTER TABLE lockers DROP FOREIGN KEY lockers_updateby;
ALTER TABLE logsdownload DROP FOREIGN KEY fk_logsDownload_catalogfiles;
ALTER TABLE logsdownload DROP FOREIGN KEY fk_logsDownload_userid;
ALTER TABLE logsdownload_article DROP FOREIGN KEY fk_logsDownload_articlefiles;
ALTER TABLE logsdownload_article DROP FOREIGN KEY fk_logsDownload_memberid;
ALTER TABLE mailserver DROP FOREIGN KEY mailserver_createby;
ALTER TABLE mailserver DROP FOREIGN KEY mailserver_updateby;
ALTER TABLE masa_berlaku_anggota DROP FOREIGN KEY masa_berlaku_anggota_createby;
ALTER TABLE masa_berlaku_anggota DROP FOREIGN KEY masa_berlaku_anggota_updateby;
ALTER TABLE master_djkn DROP FOREIGN KEY master_djkn_createby;
ALTER TABLE master_djkn DROP FOREIGN KEY master_djkn_updateby;
ALTER TABLE master_edisi_serial DROP FOREIGN KEY edisiSerial_catalog;
ALTER TABLE master_fakultas DROP FOREIGN KEY master_fakultas_createby;
ALTER TABLE master_fakultas DROP FOREIGN KEY master_fakultas_updateby;
ALTER TABLE master_jenis_identitas DROP FOREIGN KEY master_jenis_identitas_createby;
ALTER TABLE master_jenis_identitas DROP FOREIGN KEY master_jenis_identitas_updateby;
ALTER TABLE master_jurusan DROP FOREIGN KEY master_jurusan_createby;
ALTER TABLE master_jurusan DROP FOREIGN KEY master_jurusan_fakultas;
ALTER TABLE master_jurusan DROP FOREIGN KEY master_jurusan_updateby;
ALTER TABLE master_kelas_besar DROP FOREIGN KEY master_kelas_besar_createby;
ALTER TABLE master_kelas_besar DROP FOREIGN KEY master_kelas_besar_updateby;
ALTER TABLE master_kependudukan DROP FOREIGN KEY master_kependudukan_createby;
ALTER TABLE master_kependudukan DROP FOREIGN KEY master_kependudukan_updateby;
ALTER TABLE master_loker DROP FOREIGN KEY master_loker_createby;
ALTER TABLE master_loker DROP FOREIGN KEY master_loker_locations;
ALTER TABLE master_loker DROP FOREIGN KEY master_loker_updateby;
ALTER TABLE master_pekerjaan DROP FOREIGN KEY master_pekerjaan_createby;
ALTER TABLE master_pekerjaan DROP FOREIGN KEY master_pekerjaan_updateby;
ALTER TABLE master_pendidikan DROP FOREIGN KEY master_pendidikan_createby;
ALTER TABLE master_pendidikan DROP FOREIGN KEY master_pendidikan_updateby;
ALTER TABLE master_program_studi DROP FOREIGN KEY master_program_studi_createby;
ALTER TABLE master_program_studi DROP FOREIGN KEY master_program_studi_jurusan;
ALTER TABLE master_program_studi DROP FOREIGN KEY master_program_studi_updateby;
ALTER TABLE master_range_umur DROP FOREIGN KEY master_range_umur_createby;
ALTER TABLE master_range_umur DROP FOREIGN KEY master_range_umur_updateby;
ALTER TABLE master_status_perkawinan DROP FOREIGN KEY master_status_perkawinan_createby;
ALTER TABLE master_status_perkawinan DROP FOREIGN KEY master_status_perkawinan_updateby;
ALTER TABLE member_fields DROP FOREIGN KEY member_fields_createby;
ALTER TABLE member_fields DROP FOREIGN KEY member_fields_updateby;
ALTER TABLE member_perpanjangan DROP FOREIGN KEY member_perpanjangan_createby;
ALTER TABLE member_perpanjangan DROP FOREIGN KEY member_perpanjangan_member;
ALTER TABLE member_perpanjangan DROP FOREIGN KEY member_perpanjangan_updateby;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_createby;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_jeniskelamin;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_locationloans;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_location_id;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_masaberlaku;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_pekerjaan;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_pendidikan;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_status;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_TujuanKunjungan_Id;
ALTER TABLE memberguesses DROP FOREIGN KEY memberguesses_updateby;
ALTER TABLE memberloanauthorizecategory DROP FOREIGN KEY FKCB16B2E75DD8E7A8;
ALTER TABLE memberloanauthorizecategory DROP FOREIGN KEY FKCB16B2E7A5EDFBF6;
ALTER TABLE memberloanauthorizecategory DROP FOREIGN KEY memberloanauthorizecategory_createby;
ALTER TABLE memberloanauthorizecategory DROP FOREIGN KEY memberloanauthorizecategory_updateby;
ALTER TABLE memberloanauthorizelocation DROP FOREIGN KEY memberloanauthorizelocation_createby;
ALTER TABLE memberloanauthorizelocation DROP FOREIGN KEY memberloanauthorizelocation_loc;
ALTER TABLE memberloanauthorizelocation DROP FOREIGN KEY memberloanauthorizelocation_member;
ALTER TABLE memberloanauthorizelocation DROP FOREIGN KEY memberloanauthorizelocation_updateby;
ALTER TABLE memberrules DROP FOREIGN KEY memberrules_createby;
ALTER TABLE memberrules DROP FOREIGN KEY memberrules_updateby;
ALTER TABLE members DROP FOREIGN KEY FK418999036ADC8006;
ALTER TABLE members DROP FOREIGN KEY members_createby;
ALTER TABLE members DROP FOREIGN KEY members_education;
ALTER TABLE members DROP FOREIGN KEY members_fakultas;
ALTER TABLE members DROP FOREIGN KEY members_identitytype;
ALTER TABLE members DROP FOREIGN KEY members_jenispermohonan;
ALTER TABLE members DROP FOREIGN KEY members_jenis_anggota;
ALTER TABLE members DROP FOREIGN KEY members_jenjang_pendidikan;
ALTER TABLE members DROP FOREIGN KEY members_jurusan;
ALTER TABLE members DROP FOREIGN KEY members_kelassiswa;
ALTER TABLE members DROP FOREIGN KEY members_programstudi;
ALTER TABLE members DROP FOREIGN KEY members_statusanggota;
ALTER TABLE members DROP FOREIGN KEY members_status_perkawinan;
ALTER TABLE members DROP FOREIGN KEY members_updateby;
ALTER TABLE members DROP FOREIGN KEY member_agama;
ALTER TABLE members DROP FOREIGN KEY member_job;
ALTER TABLE members DROP FOREIGN KEY member_sex;
ALTER TABLE members DROP FOREIGN KEY member_unit_kerja;
ALTER TABLE members_form DROP FOREIGN KEY members_form_createby;
ALTER TABLE members_form DROP FOREIGN KEY members_form_field;
ALTER TABLE members_form DROP FOREIGN KEY members_form_perpus;
ALTER TABLE members_form DROP FOREIGN KEY members_form_updateby;
ALTER TABLE members_form_list DROP FOREIGN KEY members_form_list_createby;
ALTER TABLE members_form_list DROP FOREIGN KEY members_form_list_field;
ALTER TABLE members_form_list DROP FOREIGN KEY members_form_list_perpus;
ALTER TABLE members_form_list DROP FOREIGN KEY members_form_list_updateby;
ALTER TABLE members_info_form DROP FOREIGN KEY members_info_form_createby;
ALTER TABLE members_info_form DROP FOREIGN KEY members_info_form_field;
ALTER TABLE members_info_form DROP FOREIGN KEY members_info_form_perpus;
ALTER TABLE members_info_form DROP FOREIGN KEY members_info_form_updateby;
ALTER TABLE members_loan_form DROP FOREIGN KEY members_loan_form_createby;
ALTER TABLE members_loan_form DROP FOREIGN KEY members_loan_form_field;
ALTER TABLE members_loan_form DROP FOREIGN KEY members_loan_form_perpus;
ALTER TABLE members_loan_form DROP FOREIGN KEY members_loan_form_updateby;
ALTER TABLE members_loanreturn_form DROP FOREIGN KEY members_loanreturn_form_createby;
ALTER TABLE members_loanreturn_form DROP FOREIGN KEY members_loanreturn_form_field;
ALTER TABLE members_loanreturn_form DROP FOREIGN KEY members_loanreturn_form_perpus;
ALTER TABLE members_loanreturn_form DROP FOREIGN KEY members_loanreturn_form_updateby;
ALTER TABLE members_online_form DROP FOREIGN KEY members_online_form_createby;
ALTER TABLE members_online_form DROP FOREIGN KEY members_online_form_field;
ALTER TABLE members_online_form DROP FOREIGN KEY members_online_form_perpus;
ALTER TABLE members_online_form DROP FOREIGN KEY members_online_form_updateby;
ALTER TABLE members_online_form_edit DROP FOREIGN KEY members_online_form_edit_createby;
ALTER TABLE members_online_form_edit DROP FOREIGN KEY members_online_form_edit_field;
ALTER TABLE members_online_form_edit DROP FOREIGN KEY members_online_form_edit_perpus;
ALTER TABLE members_online_form_edit DROP FOREIGN KEY members_online_form_edit_updateby;
ALTER TABLE membersonline DROP FOREIGN KEY FK_branch;
ALTER TABLE membersonline DROP FOREIGN KEY FK_locationloan;
ALTER TABLE membersonline DROP FOREIGN KEY membersonline_createby;
ALTER TABLE membersonline DROP FOREIGN KEY membersonline_updateby;
ALTER TABLE menu DROP FOREIGN KEY menu_createby;
ALTER TABLE menu DROP FOREIGN KEY menu_ibfk_1;
ALTER TABLE menu DROP FOREIGN KEY menu_updateby;
ALTER TABLE migration DROP FOREIGN KEY migration_createby;
ALTER TABLE migration DROP FOREIGN KEY migration_updateby;
ALTER TABLE modules DROP FOREIGN KEY FK578D5FF54CBDA5AE;
ALTER TABLE modules DROP FOREIGN KEY FK578D5FF550C48F63;
ALTER TABLE modules DROP FOREIGN KEY modules_createby;
ALTER TABLE modules DROP FOREIGN KEY modules_updateby;
ALTER TABLE opacfields DROP FOREIGN KEY opacfields_createby;
ALTER TABLE opacfields DROP FOREIGN KEY opacfields_updateby;
ALTER TABLE opaclogs DROP FOREIGN KEY opaclogs_createby;
ALTER TABLE opaclogs DROP FOREIGN KEY opaclogs_updateby;
ALTER TABLE opaclogs DROP FOREIGN KEY opaclogs_userid;
ALTER TABLE opaclogs_keyword DROP FOREIGN KEY opaclogs_keyword_opaclogsid;
ALTER TABLE partners DROP FOREIGN KEY partners_createby;
ALTER TABLE partners DROP FOREIGN KEY partners_updateby;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_cli;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_collection;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_collectionloan;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_createby;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_jenisdenda;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_jenispelanggaran;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_member;
ALTER TABLE pelanggaran DROP FOREIGN KEY pelanggaran_updateby;
ALTER TABLE pengiriman DROP FOREIGN KEY pengiriman_createby;
ALTER TABLE pengiriman DROP FOREIGN KEY pengiriman_updateby;
ALTER TABLE pengiriman_koleksi DROP FOREIGN KEY pengirimankoleksi_collectionid;
ALTER TABLE pengiriman_koleksi DROP FOREIGN KEY pengirimankoleksi_createby;
ALTER TABLE pengiriman_koleksi DROP FOREIGN KEY pengirimankoleksi_updateby;
ALTER TABLE pengiriman_koleksi DROP FOREIGN KEY pengiriman_cetak_id;
ALTER TABLE peraturan_peminjaman_hari DROP FOREIGN KEY pp_hari_createby;
ALTER TABLE peraturan_peminjaman_hari DROP FOREIGN KEY pp_hari_updateby;
ALTER TABLE peraturan_peminjaman_tanggal DROP FOREIGN KEY pp_tanggal_createby;
ALTER TABLE peraturan_peminjaman_tanggal DROP FOREIGN KEY pp_tanggal_updateby;
ALTER TABLE propinsi DROP FOREIGN KEY propinsi_createby;
ALTER TABLE propinsi DROP FOREIGN KEY propinsi_updateby;
ALTER TABLE publishers DROP FOREIGN KEY publishers_createby;
ALTER TABLE publishers DROP FOREIGN KEY publishers_updateby;
ALTER TABLE quarantined_auth_data DROP FOREIGN KEY quarantined_auth_data_auth_header;
ALTER TABLE quarantined_auth_data DROP FOREIGN KEY quarantined_auth_data_createby;
ALTER TABLE quarantined_auth_data DROP FOREIGN KEY quarantined_auth_data_updateby;
ALTER TABLE quarantined_auth_header DROP FOREIGN KEY quarantined_auth_header_createby;
ALTER TABLE quarantined_auth_header DROP FOREIGN KEY quarantined_auth_header_updateby;
ALTER TABLE quarantined_catalog_ruas DROP FOREIGN KEY quarantined_catalog_ruas_catalogs;
ALTER TABLE quarantined_catalog_ruas DROP FOREIGN KEY quarantined_catalog_ruas_createby;
ALTER TABLE quarantined_catalog_ruas DROP FOREIGN KEY quarantined_catalog_ruas_updateby;
ALTER TABLE quarantined_catalog_subruas DROP FOREIGN KEY quarantined_catalog_subruas_createby;
ALTER TABLE quarantined_catalog_subruas DROP FOREIGN KEY quarantined_catalog_subruas_ruas;
ALTER TABLE quarantined_catalog_subruas DROP FOREIGN KEY quarantined_catalog_subruas_updateby;
ALTER TABLE quarantined_catalogs DROP FOREIGN KEY quarantined_catalogs_createby;
ALTER TABLE quarantined_catalogs DROP FOREIGN KEY quarantined_catalogs_member;
ALTER TABLE quarantined_catalogs DROP FOREIGN KEY quarantined_catalogs_qby;
ALTER TABLE quarantined_catalogs DROP FOREIGN KEY quarantined_catalogs_updateby;
ALTER TABLE quarantined_collections DROP FOREIGN KEY quarantined_collections_createby;
ALTER TABLE quarantined_collections DROP FOREIGN KEY quarantined_collections_qby;
ALTER TABLE quarantined_collections DROP FOREIGN KEY quarantined_collections_updateby;
ALTER TABLE quarantined_pengiriman DROP FOREIGN KEY quarantined_pengiriman_createby;
ALTER TABLE quarantined_pengiriman DROP FOREIGN KEY quarantined_pengiriman_updateby;
ALTER TABLE readinlocation DROP FOREIGN KEY readinlocation_createby;
ALTER TABLE readinlocation DROP FOREIGN KEY readinlocation_location;
ALTER TABLE readinlocation DROP FOREIGN KEY readinlocation_updateby;
ALTER TABLE refferenceitems DROP FOREIGN KEY FKFCF3C0CBEACE6BC0;
ALTER TABLE refferenceitems DROP FOREIGN KEY refferenceitems_createby;
ALTER TABLE refferenceitems DROP FOREIGN KEY refferenceitems_updateby;
ALTER TABLE refferences DROP FOREIGN KEY refferences_createby;
ALTER TABLE refferences DROP FOREIGN KEY refferences_format;
ALTER TABLE refferences DROP FOREIGN KEY refferences_updateby;
ALTER TABLE requestcatalog DROP FOREIGN KEY requestcatalog_createby;
ALTER TABLE requestcatalog DROP FOREIGN KEY requestcatalog_member;
ALTER TABLE requestcatalog DROP FOREIGN KEY requestcatalog_updateby;
ALTER TABLE rfid_temp DROP FOREIGN KEY rfid_temp_createby;
ALTER TABLE rfid_temp DROP FOREIGN KEY rfid_temp_updateby;
ALTER TABLE rolemodule DROP FOREIGN KEY FK4533E5AE26BAF3EC;
ALTER TABLE rolemodule DROP FOREIGN KEY FK4533E5AED86F6C52;
ALTER TABLE rolemodule DROP FOREIGN KEY rolemodule_createby;
ALTER TABLE rolemodule DROP FOREIGN KEY rolemodule_updateby;
ALTER TABLE roles DROP FOREIGN KEY FK5F7A48334CBDA5AE;
ALTER TABLE roles DROP FOREIGN KEY roles_createby;
ALTER TABLE roles DROP FOREIGN KEY roles_updateby;
ALTER TABLE sentitems DROP FOREIGN KEY sentitems_cli;
ALTER TABLE serial_articlefiles DROP FOREIGN KEY serial_articlefiles_ibfk_1;
ALTER TABLE serial_articles DROP FOREIGN KEY articles_catalog;
ALTER TABLE serial_articles DROP FOREIGN KEY articles_createby;
ALTER TABLE serial_articles DROP FOREIGN KEY articles_updateby;
ALTER TABLE serial_articles_repeatable DROP FOREIGN KEY CREATE_USER;
ALTER TABLE serial_articles_repeatable DROP FOREIGN KEY SERIAL_ARTICLE_ID;
ALTER TABLE serial_articles_repeatable DROP FOREIGN KEY UPDATE_USER;
ALTER TABLE settingcatalogdetail DROP FOREIGN KEY settingcatalogdetail_createby;
ALTER TABLE settingcatalogdetail DROP FOREIGN KEY settingcatalogdetail_Field;
ALTER TABLE settingcatalogdetail DROP FOREIGN KEY settingcatalogdetail_updateby;
ALTER TABLE settingparameters DROP FOREIGN KEY settingparameters_createby;
ALTER TABLE settingparameters DROP FOREIGN KEY settingparameters_updateby;
ALTER TABLE status_anggota DROP FOREIGN KEY status_anggota_createby;
ALTER TABLE status_anggota DROP FOREIGN KEY status_anggota_updateby;
ALTER TABLE stockopname DROP FOREIGN KEY stockopname_createby;
ALTER TABLE stockopname DROP FOREIGN KEY stockopname_updateby;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_collection;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_collectionrule1;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_collectionrule2;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_colstatus1;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_colstatus2;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_createby;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_location1;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_location2;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_stockopname;
ALTER TABLE stockopnamedetail DROP FOREIGN KEY stockopnamedetail_updateby;
ALTER TABLE sumbangan DROP FOREIGN KEY sumbangan_createby;
ALTER TABLE sumbangan DROP FOREIGN KEY sumbangan_member;
ALTER TABLE sumbangan DROP FOREIGN KEY sumbangan_updateby;
ALTER TABLE sumbangan_koleksi DROP FOREIGN KEY sumbangan_koleksi_collection;
ALTER TABLE sumbangan_koleksi DROP FOREIGN KEY sumbangan_koleksi_createby;
ALTER TABLE sumbangan_koleksi DROP FOREIGN KEY sumbangan_koleksi_sumbangan;
ALTER TABLE sumbangan_koleksi DROP FOREIGN KEY sumbangan_koleksi_updateby;
ALTER TABLE survey DROP FOREIGN KEY survey_createby;
ALTER TABLE survey DROP FOREIGN KEY survey_updateby;
ALTER TABLE survey_isian DROP FOREIGN KEY survey_isian_pertanyaan;
ALTER TABLE survey_pertanyaan DROP FOREIGN KEY survey_pertanyaan_createby;
ALTER TABLE survey_pertanyaan DROP FOREIGN KEY survey_pertanyaan_survey;
ALTER TABLE survey_pertanyaan DROP FOREIGN KEY survey_pertanyaan_updateby;
ALTER TABLE survey_pilihan DROP FOREIGN KEY survey_pilihan_createby;
ALTER TABLE survey_pilihan DROP FOREIGN KEY survey_pilihan_survey_pertanyaan;
ALTER TABLE survey_pilihan DROP FOREIGN KEY survey_pilihan_updateby;
ALTER TABLE survey_pilihan_sesi DROP FOREIGN KEY survey_pilihan_sesi_pilihan;
ALTER TABLE tempnoinduk DROP FOREIGN KEY tempnoinduk_createby;
ALTER TABLE tempnoinduk DROP FOREIGN KEY tempnoinduk_updateby;
ALTER TABLE tujuan_kunjungan DROP FOREIGN KEY tujuan_kunjungan_createby;
ALTER TABLE tujuan_kunjungan DROP FOREIGN KEY tujuan_kunjungan_updateby;
ALTER TABLE user DROP FOREIGN KEY user;
ALTER TABLE user DROP FOREIGN KEY user_createby;
ALTER TABLE userloclibforcol DROP FOREIGN KEY FK_userloclibforcol_loclib;
ALTER TABLE userloclibforcol DROP FOREIGN KEY FK_userloclibforcol_user;
ALTER TABLE userloclibforcol DROP FOREIGN KEY userloclibforcol_createby;
ALTER TABLE userloclibforcol DROP FOREIGN KEY userloclibforcol_updateby;
ALTER TABLE userloclibforloan DROP FOREIGN KEY FK_userloclibforloan_loclib;
ALTER TABLE userloclibforloan DROP FOREIGN KEY FK_userloclibforloan_user;
ALTER TABLE userloclibforloan DROP FOREIGN KEY userloclibforloan;
ALTER TABLE userloclibforloan DROP FOREIGN KEY userloclibforloan_createby;
ALTER TABLE userlogs DROP FOREIGN KEY FKF49AED76753825B6;
ALTER TABLE userlogs DROP FOREIGN KEY userlogs;
ALTER TABLE userlogs DROP FOREIGN KEY userlogs_createby;
ALTER TABLE usersold DROP FOREIGN KEY FK617D3C3A6ADC8006;
ALTER TABLE usersold DROP FOREIGN KEY FK617D3C3AA5775E88;
ALTER TABLE usersold DROP FOREIGN KEY FK617D3C3AD86F6C52;
ALTER TABLE usersold DROP FOREIGN KEY users;
ALTER TABLE usersold DROP FOREIGN KEY users_createby;
ALTER TABLE worksheetfielditems DROP FOREIGN KEY FKB9A428D2352BBDA2;
ALTER TABLE worksheetfielditems DROP FOREIGN KEY FKB9A428D2EACE6BC0;
ALTER TABLE worksheetfielditems DROP FOREIGN KEY worksheetfielditems_createby;
ALTER TABLE worksheetfielditems DROP FOREIGN KEY worksheetfielditems_updateby;
ALTER TABLE worksheetfields DROP FOREIGN KEY FK1471BB4B66DFF9B4;
ALTER TABLE worksheetfields DROP FOREIGN KEY FK1471BB4BFEC5D3CC;
ALTER TABLE worksheetfields DROP FOREIGN KEY worksheetfields_createby;
ALTER TABLE worksheetfields DROP FOREIGN KEY worksheetfields_updateby;
ALTER TABLE worksheets DROP FOREIGN KEY FK3800D37D5B024CA8;
ALTER TABLE worksheets DROP FOREIGN KEY worksheets_createby;
ALTER TABLE worksheets DROP FOREIGN KEY worksheets_updateby;

-- Aktifkan kembali foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Script selesai - semua foreign key constraints telah dihapus
SELECT 'Semua foreign key constraints berhasil dihapus!' AS status;


-- ALTER TABLE statements yang benar (extracted dari data Anda):
ALTER TABLE `bacaditempat` MODIFY COLUMN `collection_id` INT NOT NULL;
ALTER TABLE `bacaditempat` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `bacaditempat` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `bookinglogs` MODIFY COLUMN `collectionId` INT;
ALTER TABLE `bookmark` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `catalog_ruas` MODIFY COLUMN `CatalogId` INT NOT NULL;
ALTER TABLE `catalog_ruas` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `catalog_subruas` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `catalog_subruas` MODIFY COLUMN `RuasID` INT NOT NULL;
ALTER TABLE `catalogfiles` MODIFY COLUMN `Catalog_id` INT NOT NULL;
ALTER TABLE `catalogfiles` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `catalogs` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `catalogs` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `collectionloanextends` MODIFY COLUMN `Collection_id` INT NOT NULL;
ALTER TABLE `collectionloanextends` MODIFY COLUMN `CollectionLoanItem_id` INT NOT NULL;
ALTER TABLE `collectionloanextends` MODIFY COLUMN `Member_id` INT NOT NULL;
ALTER TABLE `collectionloanitems` MODIFY COLUMN `Collection_id` INT NOT NULL;
ALTER TABLE `collectionloanitems` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `collectionloanitems` MODIFY COLUMN `member_id` INT NOT NULL;
ALTER TABLE `collectionloans` MODIFY COLUMN `Member_id` INT NOT NULL;
ALTER TABLE `collections` MODIFY COLUMN `Catalog_id` INT;
ALTER TABLE `collections` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `colloclib` MODIFY COLUMN `Col_id` INT NOT NULL;
ALTER TABLE `deposit_taksiran_harga` MODIFY COLUMN `ID_collections` INT;
ALTER TABLE `djkn_data` MODIFY COLUMN `Collection_id` INT;
ALTER TABLE `favorite` MODIFY COLUMN `Catalog_Id` INT;
ALTER TABLE `favorite` MODIFY COLUMN `id` INT NOT NULL;
ALTER TABLE `historydata` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `jenis_anggota` MODIFY COLUMN `DendaTenorJumlah` INT;
ALTER TABLE `jenis_anggota` MODIFY COLUMN `SuspendTenorJumlah` INT;
ALTER TABLE `keranjang_anggota` MODIFY COLUMN `Member_id` INT NOT NULL;
ALTER TABLE `keranjang_katalog` MODIFY COLUMN `Catalog_id` INT NOT NULL;
ALTER TABLE `keranjang_koleksi` MODIFY COLUMN `Collection_id` INT NOT NULL;
ALTER TABLE `kriteria_koleksi` MODIFY COLUMN `catalog_id` INT;
ALTER TABLE `master_edisi_serial` MODIFY COLUMN `Catalog_id` INT;
ALTER TABLE `master_edisi_serial` MODIFY COLUMN `id` INT NOT NULL;
ALTER TABLE `member_perpanjangan` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `member_perpanjangan` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `memberloanauthorizecategory` MODIFY COLUMN `Member_id` INT NOT NULL;
ALTER TABLE `memberloanauthorizelocation` MODIFY COLUMN `Member_id` INT NOT NULL;
ALTER TABLE `members` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `pelanggaran` MODIFY COLUMN `Collection_id` INT;
ALTER TABLE `pelanggaran` MODIFY COLUMN `CollectionLoanItem_id` INT;
ALTER TABLE `pelanggaran` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `pengiriman_koleksi` MODIFY COLUMN `Collection_id` INT;
ALTER TABLE `peraturan_peminjaman_hari` MODIFY COLUMN `DendaTenorJumlah` INT;
ALTER TABLE `peraturan_peminjaman_hari` MODIFY COLUMN `SuspendTenorJumlah` INT;
ALTER TABLE `peraturan_peminjaman_tanggal` MODIFY COLUMN `DendaTenorJumlah` INT;
ALTER TABLE `peraturan_peminjaman_tanggal` MODIFY COLUMN `SuspendTenorJumlah` INT;
ALTER TABLE `quarantined_catalog_ruas` MODIFY COLUMN `CatalogId` INT NOT NULL;
ALTER TABLE `quarantined_catalog_ruas` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `quarantined_catalog_subruas` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `quarantined_catalog_subruas` MODIFY COLUMN `RuasID` INT NOT NULL;
ALTER TABLE `quarantined_catalogs` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `quarantined_catalogs` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `quarantined_collections` MODIFY COLUMN `Catalog_id` INT;
ALTER TABLE `quarantined_collections` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `quarantined_pengiriman` MODIFY COLUMN `Collection_ID` INT NOT NULL;
ALTER TABLE `readinlocation` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `requestcatalog` MODIFY COLUMN `MemberID` INT;
ALTER TABLE `sentitems` MODIFY COLUMN `CollectionLoanItem_id` INT;
ALTER TABLE `serial_articlefiles` MODIFY COLUMN `Articles_id` INT NOT NULL;
ALTER TABLE `serial_articlefiles` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `serial_articles` MODIFY COLUMN `Catalog_id` INT;
ALTER TABLE `serial_articles` MODIFY COLUMN `id` INT NOT NULL;
ALTER TABLE `serial_articles_repeatable` MODIFY COLUMN `serial_article_ID` INT NOT NULL;
ALTER TABLE `smslogs` MODIFY COLUMN `recieverID` INT;
ALTER TABLE `stockopnamedetail` MODIFY COLUMN `CollectionID` INT NOT NULL;
ALTER TABLE `stockopnamedetail` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `sumbangan` MODIFY COLUMN `Member_id` INT;
ALTER TABLE `sumbangan_koleksi` MODIFY COLUMN `Collection_id` INT;
ALTER TABLE `tempnoinduk` MODIFY COLUMN `ID` INT NOT NULL;
ALTER TABLE `worksheets` MODIFY COLUMN `SuspendTenorJumlah` INT;


